[project]
name = "spatial-cimis-eto"
version = "0.1.0"
description = "pyscimis: Automated time-series data extraction tool for spatial CIMIS dataset"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "requests",
    "rasterio",
    "geopandas",
    "xarray",
    "numpy",
    "matplotlib",
]

[tool.setuptools.packages.find]
where = ["src"]